const baseRecipes=[
{id:'gougeres',title:'Gougères – sajtos fánk',cat:'Előételek',servings:4,total:'48 perc',image:'gougeres.jpg',accessories:['kneading'],ingredients:[['80 g','vaj'],['150 g','liszt'],['4 db','tojás'],['120 + 30 g','reszelt Comté sajt'],['1 csipet','reszelt szerecsendió'],['','só'],['25 cl','víz']],stepAccessories:['kneading','kneading','kneading'],steps:['Melegítsd elő a sütőt 180 °C-ra. A dagasztó-/aprítókéses edénybe tedd a vizet, a vajat és a sót. Működtesd 3-as sebességen, 90 °C-on 8 percig. Add hozzá a lisztet, majd 6-os sebességen keverd 2 percig.','Tedd vissza a masszát a dagasztó-/aprítókéses edénybe, és működtesd 7-es sebességen. Add hozzá egyenként a tojásokat, majd a 120 g sajtot és a szerecsendiót.','Sütőpapíros tepsire kanalazz kis halmokat, szórd meg a maradék sajttal, és süsd 18–20 percig.'],program:['90 °C • 3-as sebesség • 8 perc','6-os sebesség • 2 perc','7-es sebesség • 2 + 1 perc'],note:'A sajtok variálásával az ízeket is változtathatod.'},
{id:'guacamole',title:'Guacamole',cat:'Előételek',servings:4,total:'5 perc',image:'guacamole.jpg',accessories:['ultrablade'],ingredients:[['3 db','nagyon érett avokádó'],['1 db','lilahagyma'],['1 gerezd','fokhagyma'],['1 ek','konzerv paradicsom-pép'],['1 tk','Tabasco®'],['1 db','lime leve'],['','só, bors']],stepAccessories:['ultrablade','ultrablade','ultrablade','ultrablade','ultrablade'],steps:['Hámozd meg a lilahagymát és a fokhagymát, majd vágd négyfelé.','Hámozd meg az avokádókat, és távolítsd el a magokat.','Az Ultrablade késsel 11-es sebességen aprítsd a hagymát és a fokhagymát 10 másodpercig.','Add hozzá az avokádót, a paradicsompépet, a Tabascót és a lime levét. Sózd, borsozd.','7-es sebességen turmixold 30 másodpercig.'],program:['Ultrablade • 11-es sebesség • 10 mp','7-es sebesség • 30 mp'],note:'Enyhébb változathoz a Tabascót édes paprikára cserélheted.'},
{id:'houmous',title:'Hummusz',cat:'Előételek',servings:'4–6',total:'9 perc',image:'houmous.jpg',accessories:['ultrablade'],ingredients:[['550 g','konzerv csicseriborsó (nettó)'],['2 gerezd','fokhagyma'],['1 db','citrom leve'],['10 cl','olívaolaj'],['1 késhegynyi','őrölt kömény'],['1 tk','tahini (opcionális)'],['','só']],stepAccessories:['ultrablade','ultrablade','ultrablade'],steps:['Csöpögtesd le a csicseriborsót, és hámozd meg a fokhagymát.','Az Ultrablade késsel tedd be a hozzávalókat, majd 12-es sebességen turmixold 3 percig.','Hűtve tálald.'],program:['Ultrablade • 12-es sebesség • 3 perc'],note:'Tálaláskor locsolj rá kevés olívaolajat.'},
{id:'salmon',title:'Füstölt lazacos mousse pohárban',cat:'Előételek',servings:'4–6',total:'8 perc',image:'salmon.jpg',accessories:['beater','ultrablade'],ingredients:[['250 g','füstölt lazac'],['180 g','mascarpone'],['25 cl','30%-os habtejszín'],['1 db','lime leve'],['10 szál','snidling']],stepAccessories:['beater','ultrablade','ultrablade'],steps:['A lehűtött edényben a habverőbetéttel, dugó nélkül 7-es sebességen verd fel a tejszínt 2 perc 30 másodpercig.','Cseréld a betétet Ultrablade késre. Tedd bele a lazacot, mascarponét és lime-levet, majd 12-es sebességen turmixold 30 másodpercig.','Óvatosan forgasd bele a felvert tejszínt, oszd poharakba, és hűtsd le.'],program:['7-es sebesség • 2:30','12-es sebesség • 2 × 30 mp'],note:'Lazac helyett füstölt pisztráng is használható.'},
{id:'zucchini',title:'Cukkinitekercsek friss kecskesajttal',cat:'Előételek',servings:4,total:'43 perc',image:'zucchini.jpg',accessories:['ultrablade','steam'],ingredients:[['2 nagy','cukkini'],['200 g','friss kecskesajt'],['3 szál','turbolya'],['10 szál','snidling'],['10 szál','petrezselyem'],['2 db','újhagyma'],['4 ek','olívaolaj'],['2 ek','citromlé'],['12 db','ehető szegfű'],['','só, bors']],stepAccessories:['steam','ultrablade','ultrablade'],steps:['Vágj kb. 1 mm vastag cukkiniszalagokat, majd a gőzkosárban Steam P1 programon párold 10 percig.','Az Ultrablade késsel aprítsd az újhagymát és a fűszernövényeket. Add hozzá a kecskesajtot és a fűszereket.','Töltsd meg a cukkiniszalagokat, tekerd fel, majd citromos-olívaolajos öntettel tálald.'],program:['Steam P1 • 10 perc','Ultrablade • 8-as sebesség'],note:'Az eredeti recept ehető szegfűvel készül.'},
{id:'samosas',title:'Húsos szamósza',cat:'Előételek',servings:4,total:'30 perc',image:'samosas.jpg',accessories:['ultrablade','mixer'],ingredients:[['250 g','marhahús'],['250 g','sárgarépa'],['1 gerezd','fokhagyma'],['1 db','hagyma'],['5 cl','olívaolaj'],['10 cl','alaplé'],['6 lap','brick tésztalap'],['2 db','tojásfehérje'],['','só, bors']],stepAccessories:['ultrablade','mixer','mixer'],steps:['A húst az Ultrablade késsel 12-es sebességen aprítsd 10 másodpercig.','Aprítsd a zöldségeket, majd keverőlapáttal Slow cook P1 programon főzd 130 °C-on 5 percig, add hozzá a húst és az alaplevet, majd további 12 percig főzd.','Töltsd a brick lapokat, hajtogasd háromszög alakúra, és süsd ki vagy süsd sütőben.'],program:['Ultrablade • 12-es sebesség • 10 mp','Slow cook P1 • 130 °C • 5 + 12 perc']},
{id:'scones',title:'Cheddar–snidling scone',cat:'Előételek',servings:'50 db',total:'1 óra 08 perc',image:'scones.jpg',accessories:['kneading'],ingredients:[['250 g','liszt'],['140 g','reszelt cheddar'],['50 g','vaj'],['150 ml','tej'],['2 ek','aprított snidling'],['50 g','mustármag'],['1 csomag','sütőpor'],['1 db','tojássárgája']],stepAccessories:['kneading','kneading','kneading'],steps:['A dagasztó-/aprítókéses edényben keverd össze a hozzávalókat 8-as sebességen 1 percig, majd pihentesd 30 percig.','Nyújtsd kb. 1 cm vastagra, szaggasd ki, kend meg tojássárgájával.','180 °C-on süsd kb. 15 percig.'],program:['8-as sebesség • 1 perc'],note:'Füstölt sonkával is tálalható.'},
{id:'pumpkin',title:'Sajtos sütőtökfelfújt',cat:'Előételek',servings:6,total:'56 perc',image:'pumpkin.jpg',accessories:['ultrablade','beater'],ingredients:[['500 g','sütőtökhús'],['4 adag','ömlesztett sajt'],['2 db','hagyma'],['2 gerezd','fokhagyma'],['90 g','vaj összesen'],['4 db','tojás'],['20 cl','tej'],['40 g','liszt'],['','só, bors']],stepAccessories:['ultrablade','beater','beater'],steps:['Az Ultrablade késsel aprítsd a hagymát és a fokhagymát. Add hozzá a vajat és a sütőtököt, majd Slow cook P2 programon főzd 20 percig.','Turmixold pürévé, majd készíts béchamelt a lisztből, tejből és vajból.','A tojásfehérjét verd habbá, óvatosan forgasd a masszába, majd 180 °C-on süsd kb. 10 percig.'],program:['Slow cook P2 • 20 perc','Sauce • 90 °C • 4-es sebesség • 8 perc','7-es sebesség • 8 perc'],note:'Bluetoothos gépnél a SAUCE program kézi beállítással is kiváltható.'}
];
const recipes=[...baseRecipes,...catalog];
const accessoryInfo={
 ultrablade:{name:'Ultrablade aprítókés',url:'https://www.le-sav.com/17700-thickbox_default/couteau-et-cache-noir-pour-robot-companion-moulinex.jpg'},
 kneading:{name:'Dagasztó-/aprítókés',url:'https://dam.groupeseb.com/m/1476fa9c61642040/Medium-MS-0A19244_couteau_a_petrir_large-png.png?timestamp=20260124223435'},
 beater:{name:'Habverő',url:'https://cdn.idealo.com/folder/Product/203683/6/203683620/s4_produktbild_max_2/moulinex-fouet-double-rotation-companion-xl.jpg'},
 mixer:{name:'Keverőlapát',url:'https://dam.groupeseb.com/m/e448bc0575b19816/Digital-MS-0A19246_melangeur_large-png.png?timestamp=20250325055200'},
 steam:{name:'Gőzkosár',url:'https://www.midi-pieces-menager.fr/394319-home_default/ms-0a19203-panier-robot-cuiseur-companion.jpg'},
 fondxl:{name:'Fond XL / XL alj',url:'https://www.bpelectro.fr/bp/2741-large_default/bouchon-bol-ou-adaptateur-fond-plat-robot-companion-moulinex-ms-8030000420.jpg'}
};
const state={cat:'Mind',q:'',favorites:new Set(JSON.parse(localStorage.getItem('companion-favs')||'[]')),cook:null,step:0};
const $=s=>document.querySelector(s); const esc=s=>String(s).replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const recipeImg=r=>'assets/recipes/'+r.image; const accImg=id=>accessoryInfo[id].url;
function save(){localStorage.setItem('companion-favs',JSON.stringify([...state.favorites]));}
function cats(){return ['Mind',...new Set(recipes.map(r=>r.cat)),'Kedvencek'];}
function filtered(){const q=state.q.trim().toLowerCase();return recipes.filter(r=>{const cat=state.cat==='Mind'||(state.cat==='Kedvencek'?state.favorites.has(r.id):r.cat===state.cat);const t=(r.title+' '+r.ingredients.map(x=>x.join(' ')).join(' ')+' '+r.accessories.map(x=>accessoryInfo[x].name).join(' ')).toLowerCase();return cat&&(!q||t.includes(q));});}
function accStrip(ids){return ids.map(id=>'<div class="acc"><img src="'+accImg(id)+'" alt="'+esc(accessoryInfo[id].name)+'"><span>'+esc(accessoryInfo[id].name)+'</span></div>').join('');}
function renderAccessoryLegend(){const el=$('#accessories');if(!el)return;el.innerHTML=Object.entries(accessoryInfo).map((e,i)=>'<div class="acc-card"><span class="num">'+(i+1)+'</span><img src="'+accImg(e[0])+'" alt=""><b>'+esc(e[1].name)+'</b></div>').join('');}
function render(){
 $('#chips').innerHTML=cats().map(c=>'<button class="chip '+(state.cat===c?'active':'')+'" data-cat="'+esc(c)+'">'+esc(c)+'</button>').join('');document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{state.cat=b.dataset.cat;render()});
 const list=filtered();if($('#count'))$('#count').textContent=list.length+' recept';$('#sub').textContent='300+ recept az eredeti tartalomjegyzék alapján';
 $('#grid').innerHTML=list.length?list.map(r=>'<article class="card" data-id="'+r.id+'"><div class="art"><img src="'+recipeImg(r)+'" alt="'+esc(r.title)+'"></div><div class="card-body"><button class="heart '+(state.favorites.has(r.id)?'on':'')+'" data-heart="'+r.id+'">'+(state.favorites.has(r.id)?'♥':'♡')+'</button><h4>'+esc(r.title)+'</h4><div class="meta"><span>👥 '+esc(r.servings)+'</span><span>⏱ '+esc(r.total)+'</span></div><div class="mini-acc">'+r.accessories.map(id=>'<img src="'+accImg(id)+'" alt="'+esc(accessoryInfo[id].name)+'" title="'+esc(accessoryInfo[id].name)+'">').join('')+'</div></div></article>').join(''):'<div class="empty" style="grid-column:1/-1">Nincs találat.</div>';
 document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));document.querySelectorAll('[data-heart]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.heart)});renderAccessoryLegend();
}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);save();render();}
function openDetail(id){const r=recipes.find(x=>x.id===id);if(r.sourceOnly){$('#detailBody').innerHTML='<div class="source-detail"><div class="source-icon">📖</div><h2>'+esc(r.title)+'</h2><div class="tags"><span class="tag">'+esc(r.cat)+'</span></div><p>Ez a recept már bekerült a teljes katalógusba. A részletes magyar hozzávalók és elkészítés következő feltöltési körben kerülnek bele.</p><div class="cookbar"><button class="secondary" id="close2">Bezárás</button></div></div>';$('#detail').classList.add('show');$('#close2').onclick=()=>$('#detail').classList.remove('show');return;}$('#detailBody').innerHTML='<div class="cover"><div class="detail-art"><img src="'+recipeImg(r)+'" alt="'+esc(r.title)+'"></div><div class="title-row"><h2>'+esc(r.title)+'</h2><button class="fav" id="favDetail">'+(state.favorites.has(id)?'♥':'♡')+'</button></div><div class="tags"><span class="tag">'+esc(r.cat)+'</span><span class="tag">👥 '+esc(r.servings)+'</span><span class="tag">⏱ '+esc(r.total)+'</span></div></div><div class="accessory-box"><div class="box-head"><h3>Szükséges Companion tartozékok</h3><span>eredeti ábrák</span></div><div class="acc-list">'+accStrip(r.accessories)+'</div></div><div class="two"><div class="box"><h3>Hozzávalók</h3><ul class="ingredients">'+r.ingredients.map(x=>'<li>'+(x[0]?'<b>'+esc(x[0])+'</b> ':'')+esc(x[1])+'</li>').join('')+'</ul></div><div class="box"><h3>Elkészítés</h3><ol class="steps">'+r.steps.map((s,i)=>'<li><span class="step-num">'+(i+1)+'</span><div class="step-content">'+((r.stepAccessories&&r.stepAccessories[i])?'<div class="step-acc"><img src="'+accImg(r.stepAccessories[i])+'" alt="'+esc(accessoryInfo[r.stepAccessories[i]].name)+'"><span>'+esc(accessoryInfo[r.stepAccessories[i]].name)+'</span></div>':'')+'<div class="step-text">'+esc(String(s).replace(/^\s*\d+\.\s*/,''))+'</div></div></li>').join('')+'</ol>'+(r.program?'<div class="program"><b>Companion-beállítások</b><br>'+r.program.map(esc).join('<br>')+'</div>':'')+(r.note?'<div class="program"><b>Tipp</b><br>'+esc(r.note)+'</div>':'')+'</div></div><div class="cookbar"><button class="secondary" id="close2">Bezárás</button><button class="primary" id="startCook">▶ Főzés indítása</button></div>';
 $('#detail').classList.add('show');$('#close2').onclick=()=>$('#detail').classList.remove('show');$('#favDetail').onclick=()=>{toggleFav(id);openDetail(id)};$('#startCook').onclick=()=>startCook(id);
}
function startCook(id){state.cook=recipes.find(x=>x.id===id);state.step=0;$('#detail').classList.remove('show');$('#cook').classList.add('show');renderCook();}
function renderCook(){const r=state.cook,s=state.step;$('#cookTitle').textContent=r.title;$('#cookStepNo').textContent=(s+1)+' / '+r.steps.length;$('#cookStepTitle').textContent='Lépés '+(s+1);$('#cookStepText').textContent=r.steps[s];const aid=(r.stepAccessories&&r.stepAccessories[s])||r.accessories[0];$('#cookAccessory').innerHTML='<span>Szükséges tartozék</span><img src="'+accImg(aid)+'" alt="'+esc(accessoryInfo[aid].name)+'"><b>'+esc(accessoryInfo[aid].name)+'</b>';$('#bar').style.width=((s+1)/r.steps.length*100)+'%';$('#prev').disabled=s===0;$('#next').textContent=s===r.steps.length-1?'Kész':'Következő';}
$('#q').oninput=e=>{state.q=e.target.value;render()};$('#random').onclick=()=>{const list=filtered(),arr=list.length?list:recipes;openDetail(arr[Math.floor(Math.random()*arr.length)].id)};$('#today').onclick=$('#random').onclick;$('#goFav').onclick=()=>{state.cat='Kedvencek';render()};$('#close').onclick=()=>$('#detail').classList.remove('show');$('#cookClose').onclick=()=>$('#cook').classList.remove('show');$('#prev').onclick=()=>{if(state.step>0){state.step--;renderCook()}};$('#next').onclick=()=>{if(state.step<state.cook.steps.length-1){state.step++;renderCook()}else{$('#cook').classList.remove('show')}};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');