(()=>{
const recipes=window.CompanionRecipes||[],acc=window.CompanionAccessoryInfo||{};
const catMap=c=>c?.startsWith('Főételek /')?'Főételek':c?.startsWith('Desszertek /')?'Desszertek':c;
const p=new URLSearchParams(location.search);const wanted=p.get('cat');let q=p.get('q')||'';const raw=document.querySelector('#heading');const grid=document.querySelector('#grid');const search=document.querySelector('#search');
const filtered=()=>{let list=wanted==='Kedvencek'?recipes.filter(r=>JSON.parse(localStorage.getItem('companion-favs')||'[]').includes(r.id)):wanted?recipes.filter(r=>catMap(r.cat)===wanted):recipes;const term=q.trim().toLowerCase();if(term)list=list.filter(r=>(r.title+' '+(r.ingredients||[]).map(x=>x.join(' ')).join(' ')).toLowerCase().includes(term));return list};
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function sprite(id){const pos={steam:'0% 0%',mixer:'50% 0%',beater:'100% 0%',kneading:'0% 100%',ultrablade:'50% 100%',fondxl:'100% 100%'};return '<span class="acc-sprite" style="background-position:'+(pos[id]||'0% 0%')+'"></span>'}
function render(){const list=filtered();raw.textContent=wanted||'Összes recept';document.querySelector('#count').textContent=list.length+' recept';grid.innerHTML=list.length?list.map(r=>'<article class="card" data-id="'+r.id+'"><div class="art">'+(r.image?'<img src="assets/recipes/'+r.image+'" alt="'+esc(r.title)+'">':'<div class="placeholder"><b>📖</b><small>Eredeti recept</small></div>')+'</div><div class="body"><h3>'+esc(r.title)+'</h3><div class="meta"><span>📂 '+esc(r.cat)+'</span>'+(r.servings?'<span>👥 '+esc(r.servings)+'</span>':'')+'</div><div class="accs">'+(r.accessories||[]).map(sprite).join('')+'</div></div></article>').join(''):'<div class="empty">Ebben a kategóriában nincs találat.</div>';grid.querySelectorAll('.card').forEach(c=>c.onclick=()=>location.href='recipe.html?id='+encodeURIComponent(c.dataset.id))}
document.querySelector('#back').onclick=()=>location.href='index.html';document.querySelector('#back2').onclick=()=>history.back();search.value=q;search.oninput=e=>{q=e.target.value;history.replaceState(null,'','category.html?'+new URLSearchParams({...(wanted?{cat:wanted}:{}),...(q?{q}: {})}).toString());render()};render();
})();