(()=>{
const recipes=window.CompanionRecipes||[],acc=window.CompanionAccessoryInfo||{};const id=new URLSearchParams(location.search).get('id');const r=recipes.find(x=>x.id===id);const main=document.querySelector('#main');
function esc(s){return String(s??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
const pos={steam:'0% 0%',mixer:'50% 0%',beater:'100% 0%',kneading:'0% 100%',ultrablade:'50% 100%',fondxl:'100% 100%'};const sprite=id=>'<span class="acc-sprite" style="background-position:'+(pos[id]||'0% 0%')+'"></span>';
if(!r){main.innerHTML='<div class="section"><div class="source"><h2>A recept nem található.</h2></div></div>';throw new Error('recipe missing')}
document.title='Companion XL • '+r.title;document.querySelector('#back').onclick=()=>history.back();
if(r.sourceOnly){main.innerHTML='<section class="section"><div class="source"><div style="font-size:46px">📖</div><h1>'+esc(r.title)+'</h1><p>Ez a recept már szerepel a Companion XL teljes katalógusában. A részletes magyar hozzávalók és elkészítés feltöltése folyamatban van.</p></div></section>';return}
const favs=JSON.parse(localStorage.getItem('companion-favs')||'[]');const isFav=favs.includes(r.id);
main.innerHTML='<section class="hero"><div class="cover">'+(r.image?'<img src="assets/recipes/'+r.image+'" alt="'+esc(r.title)+'">':'')+'</div><div class="pad"><div class="titleRow"><h1>'+esc(r.title)+'</h1><button class="fav" id="fav">'+(isFav?'♥':'♡')+'</button></div><div class="tags"><span class="tag">'+esc(r.cat)+'</span><span class="tag">👥 '+esc(r.servings||'—')+'</span><span class="tag">⏱ '+esc(r.total||'—')+'</span></div></div></section><section class="section"><h2>Companion tartozékok</h2><div class="accs">'+(r.accessories||[]).map(id=>'<div class="acc">'+sprite(id)+'<b>'+esc(acc[id]?.name||id)+'</b></div>').join('')+'</div></section><div class="layout"><section class="section"><h2>Hozzávalók</h2><ul class="ingredients">'+(r.ingredients||[]).map(x=>'<li>'+(x[0]?'<b>'+esc(x[0])+'</b> ':'')+esc(x[1])+'</li>').join('')+'</ul></section><section class="section"><h2>Elkészítés</h2><ol class="steps">'+(r.steps||[]).map((s,i)=>'<li>'+(r.stepAccessories?.[i]?'<div class="acc" style="display:inline-flex;margin-bottom:7px">'+sprite(r.stepAccessories[i])+'<b>'+esc(acc[r.stepAccessories[i]]?.name||'')+'</b></div><br>':'')+esc(s)+'</li>').join('')+'</ol>'+(r.program?'<div class="program"><b>Companion-beállítások</b><br>'+r.program.map(esc).join('<br>')+'</div>':'')+(r.note?'<div class="program"><b>Tipp</b><br>'+esc(r.note)+'</div>':'')+'</section></div>';
document.querySelector('#fav').onclick=()=>{const next=new Set(JSON.parse(localStorage.getItem('companion-favs')||'[]'));next.has(r.id)?next.delete(r.id):next.add(r.id);localStorage.setItem('companion-favs',JSON.stringify([...next]));document.querySelector('#fav').textContent=next.has(r.id)?'♥':'♡'};
})();