(function(){
const topCategory=c=>c.startsWith('Főételek /')?'Főételek':c.startsWith('Desszertek /')?'Desszertek':c;
const order=['Alapreceptek','Aperitifek','Előételek','Levesek','Főételek','Köretek','Kenyerek, briósok, sós sütemények','Szószok','Desszertek','Italok','Gyerekreceptek','Gluténmentes'];
const imgs={Alapreceptek:'gougeres.jpg',Aperitifek:'guacamole.jpg',Előételek:'salmon.jpg',Levesek:'pumpkin.jpg',Főételek:'samosas.jpg',Köretek:'zucchini.jpg','Kenyerek, briósok, sós sütemények':'scones.jpg',Szószok:'houmous.jpg',Desszertek:'scones.jpg',Italok:'salmon.jpg',Gyerekreceptek:'pumpkin.jpg',Gluténmentes:'zucchini.jpg'};
function drawCategories(){
 const counts={};recipes.forEach(r=>{const c=topCategory(r.cat);counts[c]=(counts[c]||0)+1});
 const el=document.querySelector('#categoryGrid');if(!el)return;
 el.innerHTML=order.map(c=>'<article class="category-card" data-cat="'+esc(c)+'"><div class="cat-art"><img src="assets/recipes/'+imgs[c]+'" alt="'+esc(c)+'"></div><div class="cat-info"><strong>'+esc(c)+'</strong><small>'+String(counts[c]||0)+' recept</small></div></article>').join('');
 el.querySelectorAll('.category-card').forEach(card=>card.onclick=()=>showTop(card.dataset.cat));
}
function showTop(name){
 const list=recipes.filter(r=>topCategory(r.cat)===name);
 document.querySelector('#sub').textContent=list.length+' recept';
 document.querySelector('#grid').innerHTML=list.map(r=>'<article class="card" data-id="'+r.id+'"><div class="art">'+(r.image?'<img src="'+recipeImg(r)+'" alt="'+esc(r.title)+'">':'<div class="art-placeholder"><span>📖</span><small>Az eredeti recept fotója</small></div>')+'</div><div class="card-body"><button class="heart" data-heart="'+r.id+'">♡</button><h4>'+esc(r.title)+'</h4><div class="meta"><span>👥 '+esc(r.servings||'—')+'</span><span>⏱ '+esc(r.total||'—')+'</span></div></div></article>').join('');
 document.querySelectorAll('.card').forEach(c=>c.onclick=()=>openDetail(c.dataset.id));
 document.querySelector('#grid').scrollIntoView({behavior:'smooth'});
}

const translated={
'catalog-0':{title:'Vaníliás angolkrém',cat:'Alapreceptek',servings:'6 adag',total:'13 perc 30 mp',accessories:['beater'],ingredients:[['6 db','tojássárgája'],['80 g','cukor'],['50 cl','tej'],['1 tk','folyékony vanília'],],stepAccessories:['beater'],steps:['A habverőbetéttel ellátott edénybe tedd a tojássárgáját és a cukrot. Keverd 6-os sebességen 1 percig. 30 másodperc után a fedél nyílásán át add hozzá a vaníliát és a tejet.','Indítsd 4-es sebességen, 85 °C-on 12 percre. A végén hagyd kihűlni, majd tálald.'],program:['Habverő • 6-os sebesség • 1 perc','4-es sebesség • 85 °C • 12 perc']},
'catalog-1':{title:'Házi vaj',cat:'Alapreceptek',servings:'125 g',total:'4 perc 40 mp',accessories:['beater'],ingredients:[['40 cl','legalább 35%-os zsírtartalmú habtejszín']],stepAccessories:['beater'],steps:['A habverőbetéttel ellátott edénybe öntsd a tejszínt, majd 7-es sebességen dolgozd 7 percig.','Szűrd le és formázd a vajat. A visszamaradó író italokhoz vagy süteményekhez felhasználható.'],program:['Habverő • 7-es sebesség • 7 perc']},
'catalog-2':{title:'Sós kevert tészta',cat:'Alapreceptek',servings:'—',total:'7 perc',accessories:['kneading'],ingredients:[['4 db','tojás'],['170 g','liszt'],['1 csomag','sütőpor (11 g)'],['5 cl','olívaolaj'],['10 cl','fehérbor'],['1 csipet','só'],['','ízlés szerinti töltelék']],stepAccessories:['kneading'],steps:['Tedd a tojást, lisztet, sütőport, olívaolajat, fehérbort és sót a dagasztó-/aprítókéses edénybe.','Indítsd a Pastry P3 programot. Add hozzá a választott tölteléket, majd keverd 4-es sebességen 1 percig.'],program:['Pastry P3','4-es sebesség • 1 perc']},
'catalog-3':{title:'Sós égetett tészta',cat:'Alapreceptek',servings:'—',total:'12 perc',accessories:['kneading'],ingredients:[['25 cl','víz'],['80 g','vaj'],['1 csipet','só'],['150 g','liszt'],['4 db','tojás']],stepAccessories:['kneading','kneading'],steps:['A dagasztó-/aprítókéses edénybe tedd a vizet, vajat és sót. Főzd 1-es sebességen, 90 °C-on 8 percig.','Add hozzá a lisztet, és keverd 4-es sebességen 2 percig. Tedd a masszát egy tálba, majd hideg vízzel hűtsd le az edényt. Tedd vissza a masszát, és 5-ös sebességen keverd. A tojásokat egyenként add hozzá a fedél nyílásán át, majd dolgozd további 2 percig.'],program:['1-es sebesség • 90 °C • 8 perc','4-es sebesség • 2 perc','5-ös sebesség • 2 perc']},
'catalog-4':{title:'Édes égetett tészta',cat:'Alapreceptek',servings:'25–35 db',total:'12 perc',accessories:['kneading','ultrablade'],ingredients:[['25 cl','víz'],['80 g','vaj'],['40 g','cukor'],['1 csipet','só'],['150 g','liszt'],['4 db','tojás']],stepAccessories:['kneading','kneading','ultrablade'],steps:['A dagasztó-/aprítókéses edényben keverd a vizet, vajat, cukrot és sót 1-es sebességen, 90 °C-on 8 percig. Add hozzá a lisztet, majd keverd 4-es sebességen 2 percig.','Tedd a tésztát egy tálba, és hideg vízzel hűtsd le az edényt.','Tedd vissza a tésztát az Ultrablade késsel, keverd 5-ös sebességen, és add hozzá egyenként a tojásokat. Dolgozd további 2 percig.'],program:['1-es sebesség • 90 °C • 8 perc','4-es sebesség • 2 perc','Ultrablade • 5-ös sebesség • 2 perc']},
'catalog-5':{title:'Omlós tészta',cat:'Alapreceptek',servings:'28 cm-es formához',total:'2 perc 30 mp + pihentetés',accessories:['kneading'],ingredients:[['240 g','liszt'],['120 g','puha vaj'],['1 csipet','só'],['7 cl','víz']],stepAccessories:['kneading'],steps:['A dagasztó-/aprítókéses edénybe tedd a lisztet, a vajat és a sót. Keverd 6-os sebességen. 30 másodperc után add hozzá a vizet, és dolgozd addig, amíg össze nem áll, körülbelül 2 perc 30 másodpercig.','Csomagold fóliába, és pihentesd 30 percig a hűtőben.'],program:['6-os sebesség • kb. 2:30']},
'catalog-6':{title:'Linzer jellegű omlós tészta',cat:'Alapreceptek',servings:'28 cm-es formához',total:'1 perc 30 mp + pihentetés',accessories:['kneading'],ingredients:[['300 g','liszt'],['180 g','puha vaj'],['110 g','porcukor'],['1 csipet','só'],['1 db','tojás']],stepAccessories:['kneading'],steps:['A dagasztó-/aprítókéses edénybe tedd a lisztet, vajat, porcukrot és sót. Keverd 8-as sebességen 1 percig.','Add hozzá a tojást, majd keverd 6-os sebességen 30 másodpercig, amíg golyóvá áll össze.','Csomagold fóliába, és pihentesd 30 percig a hűtőben.'],program:['8-as sebesség • 1 perc','6-os sebesség • 30 mp']},
'catalog-7':{title:'Hollandi mártás',cat:'Alapreceptek',servings:'—',total:'8 perc',accessories:['beater'],ingredients:[['150 g','vaj'],['4 cl','citromlé'],['4 db','tojássárgája'],['5 cl','víz'],['','só, bors']],stepAccessories:['beater'],steps:['A habverőbetéttel ellátott edénybe tedd a kis darabokra vágott vajat, a citromlevet, a tojássárgáját és 5 cl vizet. Sózd, borsozd.','Indítsd 6-os sebességen, 70 °C-on 8 percre.'],program:['Habverő • 6-os sebesség • 70 °C • 8 perc']},
'catalog-8':{title:'Paradicsomszósz',cat:'Alapreceptek',servings:'—',total:'21 perc',accessories:['ultrablade','mixer'],ingredients:[['1 db','hagyma'],['2 gerezd','fokhagyma'],['3 cl','olaj'],['700 g','friss paradicsom'],['1 tk','oregánó'],['1 tk','cukor'],['1 ek','paradicsompüré'],['2 ek','víz'],['','só, bors']],stepAccessories:['ultrablade','mixer','ultrablade'],steps:['Az Ultrablade késsel aprítsd a negyedekre vágott hagymát és fokhagymát 11-es sebességen 10 másodpercig.','Cseréld a kést keverőlapátra, kapard le az edény falát, add hozzá az olajat, majd indítsd a Slow cook P1 programot 130 °C-on 5 percre.','Cseréld vissza az Ultrablade kést. Add hozzá a negyedelt paradicsomot, oregánót, cukrot, paradicsompürét, vizet, sót és borsot. Indítsd a Slow cook P3 programot 100 °C-on 20 percre, majd turmixold 12-es sebességen 1 percig.'],program:['Ultrablade • 11-es sebesség • 10 mp','Slow cook P1 • 130 °C • 5 perc','Slow cook P3 • 100 °C • 20 perc','Ultrablade • 12-es sebesség • 1 perc']},
'catalog-9':{title:'Étcsokoládé-ganache fűszerekkel',cat:'Alapreceptek',servings:'—',total:'8 perc 30 mp',accessories:['beater'],ingredients:[['180 g','30%-os habtejszín'],['150 g','legalább 70%-os étcsokoládé'],['30 g','vaj'],['','őrölt fűszer ízlés szerint']],stepAccessories:['beater'],steps:['A habverőbetéttel ellátott edénybe öntsd a tejszínt, add hozzá a választott fűszert, és melegítsd 3-as sebességen, 90 °C-on 5 percig.','A jelzés után add hozzá a darabokra tört csokoládét, és keverd 5-ös sebességen, 50 °C-on 3 percig.','Kapard le az edény falát, add hozzá a kockázott vajat, és keverd 6-os sebességen 30 másodpercig. Hagyd kihűlni.'],program:['Habverő • 3-as sebesség • 90 °C • 5 perc','5-ös sebesség • 50 °C • 3 perc','6-os sebesség • 30 mp']}
};
Object.keys(translated).forEach(id=>{const r=recipes.find(x=>x.id===id);if(r)Object.assign(r,translated[id],{sourceOnly:false,image:null})});

drawCategories();
document.querySelector('#allCats')?.addEventListener('click',()=>document.querySelector('#categoryGrid')?.scrollIntoView({behavior:'smooth'}));
document.querySelector('#navHome')?.addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));
document.querySelector('#navRecipes')?.addEventListener('click',()=>document.querySelector('#grid')?.scrollIntoView({behavior:'smooth'}));
document.querySelector('#navCats')?.addEventListener('click',()=>document.querySelector('#categoryGrid')?.scrollIntoView({behavior:'smooth'}));
document.querySelector('#navFav')?.addEventListener('click',()=>{state.cat='Kedvencek';render();document.querySelector('#grid')?.scrollIntoView({behavior:'smooth'})});
})();